---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pepeArenas/spring-cloudconfig-wa-tolls.git
          #username: user
          #password: pass